server:
  port: 8283

# SERVICE_REGISTRY ----------------------------------------------------------------------------------------------------
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}@${random.int}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka}

spring:
  application:
    name: product-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/product-service?useSSL=false&useUnicode=true&characterEncoding=UTF-8}
    username: postgres
    password: myPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

url:
  create-inventory-url: ${CREATE-INVENTORY-URL:http://0.0.0.0:8284/api/inventory/create-inventory}